version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - COLLECTION_NAME=${COLLECTION_NAME}
